### ISSUE TITLE
 Not in scope: ‘Arr.arrStart’

### ISSUE THREAD

**Issue by andregpss** [agentm/curryer#1]
I have tried to install `curryer-rpc` using `cabal install`, but it failed.
I think the main reason for it is that `curryer-rcp` uses `streamly` library constructors that are included only on its `0.8.1` version.
However, curryer dependencies include `streamly` library version `0.8.0 `.
The errors are:

     src\Network\RPC\Curryer\Server.hs:374:14: error:
        Not in scope: ‘Arr.arrStart’
        Perhaps you meant one of these:
          ‘Arr.aStart’ (imported from Streamly.Internal.Data.Array.Foreign.Type),
          ‘ArrT.aStart’ (imported from Streamly.Internal.Data.Array.Foreign.Mut.Type)
        Module ‘Streamly.Internal.Data.Array.Foreign.Type’ does not export ‘arrStart’.
        |
    374 |     aStart = Arr.arrStart arr
        |              ^^^^^^^^^^^^

    src\Network\RPC\Curryer\Server.hs:376:23:`` error:

    Not in scope: ‘Arr.arrStart’
    Perhaps you meant one of these:
      ‘Arr.aStart’ (imported from Streamly.Internal.Data.Array.Foreign.Type),
      ‘ArrT.aStart’ (imported from Streamly.Internal.Data.Array.Foreign.Mut.Type)
    Module ‘Streamly.Internal.Data.Array.Foreign.Type’ does not export ‘arrStart’.
        |
    376 |     aStartFPtr = case Arr.arrStart arr of
        |                       ^^^^^^^^^^^^
    
     src\Network\RPC\Curryer\Server.hs:377:36:` error:
    
        Not in scope: ‘ArrT.arrayToFptrContents’
        Module ‘Streamly.Internal.Data.Array.Foreign.Mut.Type’ does not export ‘arrayToFptrContents’.
        |
    377 |       Ptr addr -> ForeignPtr addr (ArrT.arrayToFptrContents (Arr.arrContents arr))
        |                                    ^^^^^^^^^^^^^^^^^^^^^^^^
    
    src\Network\RPC\Curryer\Server.hs:377:62: error:
    
        Not in scope: ‘Arr.arrContents’
        Module ‘Streamly.Internal.Data.Array.Foreign.Type’ does not export ‘arrContents’.
        |
    377 |       Ptr addr -> ForeignPtr addr (ArrT.arrayToFptrContents (Arr.arrContents arr))
        |                                                              ^^^^^^^^^^^^^^^

**Comment by agentm** [comment]
Indeed. Fixed in 0.2.1.

Thanks for the report!
