### ISSUE TITLE
Lack of TCP_NODELAY

### ISSUE THREAD

**Issue by nh2** [agentm/curryer#3]
Hi,

CloudHaskell / `distributed-process` was brutally slow in some cases because it did not set `TCP_NODELAY`:

https://cloud-haskell.atlassian.net/browse/DP-108

I did not spot `curryer` or `streamly` do this better; thus it feels likely that `curryer` may replicate the same mistake.

This might be useful: https://gist.github.com/nh2/9def4bcf32891a336485

**Comment by agentm** [comment]
That's a good tip. Thanks!
